# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3bb63840f2df9c6c7a44566bc39cef3f2dd858675509a16ec108ac8e19f921d2e7c8e2dcc8b385ba6b8822bab442eed59e96e99ed87faa19307e3f8da4be4ba

test:
  secret_key_base: 6f0ffcb1a23fad5e08e3b0d0a2769a231a008c3c69cd331404ba39a42416feeb85e8165ef3e54c89697461091b9851311fea956eddd9a979f30dd1e28e35fcae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
